server/build.gradle, server/src/main/java/com/cocoa/catdog/advice/GlobalExceptionAdvice.java, server/src/main/java/com/cocoa/catdog/exception/BusinessLogicException.java, server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java, server/src/main/java/com/cocoa/catdog/response/ErrorResponse.java
어떤 종류의 PR인가요?
Issue Number: #1 
response 패키지, , exeption 패키지, advice 패키지
=> be. 예외처리 관련 초기 세팅

client/src/components/InnerContainer/InnerContainer.tsx, client/src/components/OuterContainer/OuterConainer.tsx
어떤 종류의 PR인가요?
Issue Number: #11 
페이지 레이아웃을 잡는 데에 필요한 OuterContainer와 InnerContainer를 추가하였습니다.
페이지에서 용례는 [위키](https://github.com/codestates-seb/seb40_main_016/wiki/%5BClient%5D-%EA%B3%B5%ED%86%B5-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EC%82%AC%EC%9A%A9%EB%B2%95#-container-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8)에 추가하였습니다.
=> [Client] 컨테이너 컴포넌트 제작

client/src/assets/style/GloabalVariables.ts, client/src/components/Button.tsx
어떤 종류의 PR인가요?
Issue Number: #16
- 페이지에서 공통적으로 사용되는 버튼 컴포넌트가 추가되었습니다.
- 글로벌 스타일에 색상을 추가했습니다.
=> [Client] 버튼 컴포넌트 제작

client/src/assets/style/GloabalVariables.ts, client/src/components/Input.tsx
어떤 종류의 PR인가요?
Issue Number: #18 
- 페이지에서 공통적으로 사용되는 인풋 컴포넌트가 추가되었습니다.
- 글로벌 스타일에 색상을 추가했습니다.
✅ 라벨, 오류 메세지 포함
=> [Client] 인풋 컴포넌트 제작

client/src/App.tsx, client/src/components/HeaderAfter.tsx
어떤 종류의 PR인가요?
Issue Number: #12 
로그인 후, headerAfter 컴포넌트 레이아웃을 구현했습니다.
화면에서 볼 수있게 App.tsx 파일에 원래 있던 headerBefore 파일을 주석처리하고 headerAfter 파일을 추가하였습니다.
이후 로그인 여부로 분기를 나눌 생각입니다.
=> [Client] headerAfter 컴포넌트 제작

client/src/components/Header/HeaderAfter.tsx, client/src/components/Header/HeaderBefore.tsx, client/src/pages/MyPage/MyPage.tsx, client/src/pages/Shop/Shop.tsx
어떤 종류의 PR인가요?
Issue Number: #12 
* header 컴포넌트 css에 bg-color: white 추가
* header 컴포넌트 내 아이콘 각 페이지로 라우터 연결
* mypage, shop 폴더 및 파일 생성
headerBefore 컴포넌트를 화면에서 보고싶으시다면 App.tsx에 있는 주석 처리를 빼고 대신 headerAfter를 주석 처리 해주시면 됩니다!
=> [Client] header 컴포넌트 라우터 연결 

client/src/App.tsx, client/src/components/Footer/Footer.tsx
어떤 종류의 PR인가요?
Issue Number: #35 
* footer 컴포넌트 레이아웃 구현
* 팀원 이름에 깃헙 링크 추가
=> [Client] footer 컴포넌트 제작

client/src/components/Footer/Footer.tsx, client/src/components/Header/HeaderAfter.tsx, client/src/components/Header/HeaderBefore.tsx
어떤 종류의 PR인가요?
Issue Number: #35
* header 컴포넌트 z-index 값 추가
* footer 컴포넌트 position: absolute 삭제
=> [Client] header, footer 컴포넌트 css 수정

server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java, server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java, server/src/main/java/com/cocoa/catdog/order/controller/OrderController.java, server/src/main/java/com/cocoa/catdog/order/dto/OrderDto.java, server/src/main/java/com/cocoa/catdog/order/dto/OrderItemDto.java, server/src/main/java/com/cocoa/catdog/order/dto/OrderResponseDto.java, server/src/main/java/com/cocoa/catdog/order/entity/Order.java, server/src/main/java/com/cocoa/catdog/order/entity/OrderItem.java, server/src/main/java/com/cocoa/catdog/order/mapper/OrderMapper.java, server/src/main/java/com/cocoa/catdog/order/repository/OrderRepository.java, server/src/main/java/com/cocoa/catdog/order/service/OrderService.java, server/src/main/java/com/cocoa/catdog/repository/ArticleRepository.java, server/src/test/java/com/appstew/practiceMain/comment/CommentServiceUnitTest.java
어떤 종류의 PR인가요?
Issue Number: #37 
통합 후 버그 수정 및 실행테스트 완료
=> 🐛 fix : 전체적인 수정 실행완료 확인

client/src/components/Header/HeaderAfter.tsx, client/src/components/Header/MenuList.tsx, client/src/pages/Signup/Signup.tsx
어떤 종류의 PR인가요?
Issue Number: #44 
* 창 넓이가 좁아졌을 때(반응형 적용), 메뉴 아이콘들을 모달창에 포함시켰습니다.
* 반응형 적용
=> [Client] menulist 컴포넌트 제작

server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java, server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java, server/src/main/java/com/cocoa/catdog/article/entity/Article.java, server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java, server/src/main/java/com/cocoa/catdog/auth/jwt/JwtTokenizer.java, server/src/main/java/com/cocoa/catdog/dto/MultiResponseDto.java, server/src/main/java/com/cocoa/catdog/dto/PageInfo.java, server/src/main/java/com/cocoa/catdog/user/controller/UserController.java, server/src/main/java/com/cocoa/catdog/user/dto/UserResponseDto.java
어떤 종류의 PR인가요?
Issue Number: #47
=> [Server] 백엔드 2차 취합 전 appstew PR 입니다

server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java, server/src/main/java/com/cocoa/catdog/user/controller/FollowController.java, server/src/main/java/com/cocoa/catdog/user/dto/FollowInfoResponseDto.java, server/src/main/java/com/cocoa/catdog/user/dto/FollowerInfoResponseDto.java, server/src/main/java/com/cocoa/catdog/user/dto/UserResponseDto.java, server/src/main/java/com/cocoa/catdog/user/mapper/FollowMapper.java, server/src/main/java/com/cocoa/catdog/user/repository/FollowRepository.java, server/src/main/java/com/cocoa/catdog/user/service/FollowService.java, server/src/main/resources/application.yml
어떤 종류의 PR인가요?
Issue Number: #19
내 팔로우 정보 보기 및 유저 목록 표시 추가
=> [Server] 팔로우 취소 및 팔로워 정보 표시 추가

client/src/components/SortTab/SortTab.tsx
어떤 종류의 PR인가요?
Issue Number: #52 
* 메인페이지에 있는 sort 버튼 구현
* 메인페이지랑 같이 구현했는데, 기능 하나씩 나눠서 pr 올려야할것 같아 이거만 따로 먼저 올립니다.
혹시 에러나면 알려주세요!
* 아직 메인 페이지를 pr에 올리지않아 화면에서 확인은 불가능합니다.
=> [Client] sortTab 컴포넌트 제작

client/src/components/ImageCard/ImageCard.tsx, client/src/pages/Main/Main.tsx
어떤 종류의 PR인가요?
Issue Number: #57 
* imageCard 기존 width, height 타입과 고정값 삭제
* aspect-ratio, object-fit 속성으로 사진과 컴포넌트 비율 맞춤
=> [Client] imageCard 컴포넌트 및 메인페이지 css 수정

client/src/App.tsx, client/src/components/Tab/Tab.tsx, client/src/components/Tab/style.ts, client/src/pages/MyPage/MyPage.tsx, client/src/pages/MyPage/style.ts
어떤 종류의 PR인가요?
Issue Number: #68 
마이페이지와 세팅 페이지에 공통으로 사용되는 탭 컴포넌트를 만들었습니다.✨
일단 임시로 마이페이지에 부분을 적용시켜놓았습니다! 
이후 누가 되었건 맡아서 수정하시면서 이어나가면 될거 같아요💕
=> [Client] tab 컴포넌트 제작

server/build.gradle, server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java, server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java, server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepository.java, server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java, server/src/main/java/com/cocoa/catdog/comment/controller/CommentController.java, server/src/main/java/com/cocoa/catdog/comment/entity/Comment.java, server/src/main/java/com/cocoa/catdog/comment/repository/CommentLikeRepository.java, server/src/main/java/com/cocoa/catdog/comment/repository/CommentReportRepository.java, server/src/main/java/com/cocoa/catdog/comment/service/CommentService.java, server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java, server/src/main/java/com/cocoa/catdog/helper/controller/HelperController.java, server/src/main/java/com/cocoa/catdog/helper/dto/HelperDto.java, server/src/main/java/com/cocoa/catdog/helper/service/HelperService.java, server/src/main/java/com/cocoa/catdog/user/entity/User.java, server/src/main/java/com/cocoa/catdog/user/service/UserService.java, server/src/test/java/com/cocoa/catdog/comment/CommentServiceUnitTest.java
어떤 종류의 PR인가요?
- [] Bugfix
Issue Number: #66 #64
글 좋아요 취소, 좋아요 중복불가, 신고 중복불가, 쿼리별 메인페이지
=> Be.feat kugnas

server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java, server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java, server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java, server/src/main/java/com/cocoa/catdog/comment/dto/CommentResponseDto.java
=> ♻️ refactor: response 코드변경

server/src/main/java/com/cocoa/catdog/advice/GlobalExceptionAdvice.java, server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java, server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java, server/src/main/java/com/cocoa/catdog/article/entity/Article.java, server/src/main/java/com/cocoa/catdog/article/entity/Like.java, server/src/main/java/com/cocoa/catdog/article/entity/Report.java, server/src/main/java/com/cocoa/catdog/article/mapper/ArticleMapper.java, server/src/main/java/com/cocoa/catdog/article/repository/LikeRepository.java, server/src/main/java/com/cocoa/catdog/article/repository/ReportRepository.java, server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java, server/src/main/java/com/cocoa/catdog/comment/controller/CommentController.java, server/src/main/java/com/cocoa/catdog/comment/dto/CommentDto.java, server/src/main/java/com/cocoa/catdog/comment/dto/CommentResponseDto.java, server/src/main/java/com/cocoa/catdog/comment/entity/CommentReport.java, server/src/main/java/com/cocoa/catdog/comment/mapper/CommentMapper.java, server/src/main/java/com/cocoa/catdog/comment/service/CommentService.java, server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java, server/src/main/java/com/cocoa/catdog/helper/controller/HelperController.java, server/src/main/java/com/cocoa/catdog/helper/dto/HelperDto.java, server/src/main/java/com/cocoa/catdog/user/dto/UserSimpleResponseDto.java, server/src/main/java/com/cocoa/catdog/user/entity/User.java
어떤 종류의 PR인가요?
Issue Number: #82 #83 #84 #85
게시물: 좋아요, 신고, 삭제, 유저반환
임시비밀번호발송구현
=> Be.feat kugnas modify

client/src/pages/MyPage/MyPage.tsx, client/src/pages/MyPage/MyPageArticles.tsx, client/src/pages/MyPage/MyPageComments.tsx, client/src/pages/MyPage/MyPageSnacks.tsx
어떤 종류의 PR인가요?
Issue Number: #74 
* 마이페이지 프로필과 게시물탭, 댓글탭, 간식탭의 레이아웃을 제작했습니다.
인터랙션 없이 골격만 만들었으니 컴포넌트의 위치와 크기 등만 참고부탁드립니다.
마이페이지 내의 아이콘에 router 또는 navigate를 연결하셔도 됩니다.
=> [Client] 마이페이지  레이아웃 구현

client/src/App.tsx, client/src/api/shop.ts, client/src/components/Checkbox/Checkbox.tsx, client/src/components/Checkbox/style.ts, client/src/components/ImageCard/ImageCard.tsx, client/src/components/Shop/Calculator/CalcContent.tsx, client/src/components/Shop/Calculator/Calculator.tsx, client/src/components/Shop/Calculator/style.ts, client/src/components/Shop/Items/Item/Item.tsx, client/src/components/Shop/Items/Item/style.ts, client/src/components/Shop/Items/items.tsx, client/src/components/Shop/ShopInfo/ShopInfo.tsx, client/src/components/Shop/ShopInfo/style.ts, client/src/pages/Shop/Shop.tsx, client/src/pages/Shop/style.ts, client/src/types/shop.ts
어떤 종류의 PR인가요?
Issue Number: #96 
- 상점 페이지 레이아웃, 기능 추가 
- 교환시 보유 알이 차감됩니다.
- 하단에 보유 알과 선택한 상품의 총 가격, 교환후 남은 알을 볼 수 있습니다.
- 각 판매 목록은 재고만큼만 구매할 수 있습니다.
- 선택한 상품은 수량 버튼이 비활성화됩니다
- 보유 알보다 선택 상품의 가격이 더 높을 경우 교환 버튼이 비활성화 됩니다.
=> [Client] 상점 페이지 구현

client/src/components/Shop/Calculator/CalcContent.tsx, client/src/components/Shop/Calculator/style.ts, client/src/components/Shop/Items/Item/Item.tsx, client/src/components/Shop/Items/Item/style.ts, client/src/components/Shop/Items/items.tsx, client/src/components/Shop/ShopInfo/style.ts
어떤 종류의 PR인가요?
- 상점 페이지 반응형을 구현했습니다.
=> [Client] 상점 페이지 반응형 구현

server/src/main/java/com/cocoa/catdog/comment/controller/CommentController.java, server/src/main/java/com/cocoa/catdog/comment/repository/CommentRepository.java, server/src/main/java/com/cocoa/catdog/comment/service/CommentService.java
=> 🐛 bug: 댓글조회오류(게시물이 달라도 같은 댓글들 조회) 수정

server/.gitignore, server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java, server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepository.java, server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java, server/src/main/java/com/cocoa/catdog/user/repository/UserRepository.java
어떤 종류의 PR인가요?
Issue Number: #99
article의 content 중 검색어를 포함한 글 목록을 리턴합니다.
=> Be.feat search article by content containing search keyword

server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
=> 🐛 bug: 글목록버그수정

server/src/main/resources/application.yml
=> Be.fix yml

server/src/main/resources/application.yml
=> ♻️  fix: application.yml 수정2

client/src/api/comment.ts, client/src/components/Detail/ArticleLikeAndSnack/ArticleLikeAndSnack.tsx, client/src/components/Detail/CommentAdd/CommentAdd.tsx, client/src/components/Detail/Comments/Comments.tsx, client/src/components/Detail/ExtraFeatureModal.tsx/ExtraFeatureModal.tsx, client/src/components/Detail/ReactionBtn/ReactionBtn.tsx
어떤 종류의 PR인가요?
Issue Number: #80
- 내 글일때는 구독 버튼이 사라지도록 처리했습니다.
- 로그인 안했을 때, 구독, 좋아요, 간식, 댓글제출 버튼이 비활성화되도록 처리했습니다!
(로그인 안해도 버튼은 있어야 기능이 있는걸 알거 같더라고요! 
그래서 남겨두고 alert만 띄우는 방향으로 해봤어요 ☺️)
- 신고 버튼은 로그인 안했을 시 disabled 처리했습니다.
🙋🏻‍♀️
-로그인 > 상세페이지 기능이용 > 로그아웃 > 다시 상세페이지 이용
하면 바로 기능 비활성화 반영이 바로 되게 하려면 또 별도 처리가 필요할거 같더라고요
그래서 말인데 로그아웃을 하면 한번 사이트 소ㅑ악! 새로고침 하는거 어떨까용?
=> [Client] 글 상세 페이지 케이스 대응

client/src/App.tsx, client/src/pages/MyPage/MyPage.tsx
어떤 종류의 PR인가요?
마이페이지에 설정 페이지 연결
=> [Client] 마이페이지에 설정 페이지 연결

client/src/pages/Setting/style.ts
=> 💄 style: 푸터와 겹쳐보이는 문제 해결

server/src/main/java/com/cocoa/catdog/CatdogApplication.java, server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java, server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java, server/src/main/java/com/cocoa/catdog/config/AsyncConfig.java, server/src/main/java/com/cocoa/catdog/message/EmitterRepository.java, server/src/main/java/com/cocoa/catdog/message/EmitterRepositoryImpl.java, server/src/main/java/com/cocoa/catdog/message/Event.java, server/src/main/java/com/cocoa/catdog/message/EventListener.java, server/src/main/java/com/cocoa/catdog/message/EventRepository.java, server/src/main/java/com/cocoa/catdog/message/SseController.java, server/src/main/java/com/cocoa/catdog/message/SseEmitterRepository.java, server/src/main/java/com/cocoa/catdog/message/SseEmitterService.java, server/src/main/java/com/cocoa/catdog/message/SseEventRepository.java
어떤 종류의 PR인가요?
Issue Number: #127
=> ✨ feat: SSE 구현 및 비동기처리(V1)

server/src/main/java/com/cocoa/catdog/article/entity/Article.java, server/src/main/java/com/cocoa/catdog/comment/dto/CommentResponseDto.java, server/src/main/java/com/cocoa/catdog/comment/mapper/CommentMapper.java, server/src/main/java/com/cocoa/catdog/item/controller/ItemController.java, server/src/main/java/com/cocoa/catdog/item/service/ItemService.java, server/src/main/java/com/cocoa/catdog/order/dto/OrderItemResponseDto.java, server/src/main/java/com/cocoa/catdog/order/entity/OrderItem.java, server/src/main/java/com/cocoa/catdog/order/mapper/OrderMapper.java, server/src/main/java/com/cocoa/catdog/user/controller/UserController.java, server/src/main/java/com/cocoa/catdog/user/dto/UserProfileResponseDto.java, server/src/main/java/com/cocoa/catdog/wallet/controller/GiveTakeController.java, server/src/main/java/com/cocoa/catdog/wallet/dto/GiveTakeDto.java, server/src/main/java/com/cocoa/catdog/wallet/dto/GiveTakeResponseDto.java, server/src/main/java/com/cocoa/catdog/wallet/entity/GiveTake.java, server/src/main/java/com/cocoa/catdog/wallet/entity/Wallet.java, server/src/main/java/com/cocoa/catdog/wallet/mapper/GiveTakeMapper.java, server/src/main/java/com/cocoa/catdog/wallet/repository/GiveTakeRepository.java, server/src/main/java/com/cocoa/catdog/wallet/service/GiveTakeService.java
어떤 종류의 PR인가요?
Issue Number: #118
=> Be.feat dto

server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java, server/src/main/java/com/cocoa/catdog/article/Dto/ArticleImgDto.java, server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java, server/src/main/java/com/cocoa/catdog/article/entity/Article.java, server/src/main/java/com/cocoa/catdog/article/entity/ArticleImg.java, server/src/main/java/com/cocoa/catdog/article/mapper/ArticleImgMapper.java, server/src/main/java/com/cocoa/catdog/article/mapper/ArticleMapper.java, server/src/main/java/com/cocoa/catdog/article/repository/ArticleImgRepository.java, server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java, server/src/main/java/com/cocoa/catdog/article/service/FileHandler.java, server/src/main/java/com/cocoa/catdog/config/CommonUtils.java, server/src/main/java/com/cocoa/catdog/config/aws/S3Uploader.java
- article 이미지 리스트 업로드, 글 상세조회까지 구현되었고 매핑 정상 작동 됩니다.
- 파일은 s3에 articleImages/ 폴더 안에 파일이름.{jpg or png} 형태로 저장됩니다.
- article 이미지 파일 없이 글만 쓸 경우 발생하는 버그를 제거하였습니다.
- formdata 에서 POST 요청 시 postDto 만 체크하고 files 키는 체크하지 않으면 됩니다.
- (files를 체크했는데 file을 선택하지 않으면 exception 이 뜹니다.)
- 
이미지 수정과 삭제는 추후 업데이트하겠습니다.
어떤 종류의 PR인가요?
Issue Number: #105
=> ♻️ refactor: 이미지 업로드 리팩터 #105

server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java, server/src/main/java/com/cocoa/catdog/article/mapper/ArticleMapper.java, server/src/main/java/com/cocoa/catdog/comment/dto/CommentResponseDto.java, server/src/main/java/com/cocoa/catdog/comment/mapper/CommentMapper.java
어떤 종류의 PR인가요?
Issue Number: #118
=> ✨ feat: 이미지링크로 반환하도록 구현

client/src/types/article.ts
어떤 종류의 PR인가요?
* api image 변경 내용 타입 지정
=> [Client] api 수정 type 변경

client/src/pages/Main/Main.tsx
어떤 종류의 PR인가요?
* 메인페이지 api 적용 경로 수정
=> [Client] 메인페이지 api 적용 경로 수정

client/src/components/Detail/ArticleLikeAndSnack/ArticleLikeAndSnack.tsx, client/src/components/Detail/SnackGiver/SnackGiver.tsx, client/src/components/Modal/style.ts
어떤 종류의 PR인가요?
Issue Number: #80
-본인 계정 글에 간식 버튼을 삭제했습니다.
-기존 모달에서 반응형 분기에서 배경 x 버튼이 모달창과 겹치는 현상을 개선했습니다.
=> [Client] 본인 계정 간식 주기 막음

client/src/App.tsx, client/src/components/Articles/PhotoUpload/PhotoUpload.tsx, client/src/components/Articles/WriteArticle/WriteArticle.tsx, client/src/pages/Articles/NewArticle.tsx
어떤 종류의 PR인가요?
- WriteArticle 슬라이더 사용 부분 오류 해결
- 글 수정시 기존 글 정보 받아오는 부분 API에 맞게 수정
- 글 작성, 수정 완료 후 메인 페이지면 새로고침, 아니면 모달 닫기로 수정
- 수정 모달 껐다 키면 사진 안불러오는 오류 & 미리보기 창 안끄고 모달 껐다 키면 미리보기 창 켜져있는 오류 수정
=> [Client] 글 작성 페이지 오류 수정

client/src/api/user.ts, client/src/components/Input/Input.tsx, client/src/components/Setting/ChangePassword/ChangePassword.tsx, client/src/components/Setting/DeleteAccount/DeleteAccount.tsx, client/src/pages/Setting/Setting.tsx
어떤 종류의 PR인가요?
- 인풋 컴포넌트에 onBlur 함수 추가
- 비밀번호 변경시 이전 비밀번호 체크
- 회원탈퇴시 DB에서 삭제가 아닌 회원 상태를 변경하는 API로 요청하도록 수정
=> [Client] 설정 페이지 비밀번호 변경, 회원 탈퇴 수정

client/src/components/Shop/Items/Item/Item.tsx, client/src/pages/Shop/Shop.tsx
어떤 종류의 PR인가요?
상품 수량이 재고보다 많거나 음수인 경우 제한
=> [Client] 상품 수량이 재고보다 많거나 음수인 경우 제한

server/build.gradle, server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java, server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepository.java, server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustom.java, server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustomImpl.java, server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java, server/src/main/java/com/cocoa/catdog/config/QuerydslConfiguration.java, server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java, server/src/main/java/com/cocoa/catdog/wallet/service/GiveTakeService.java, server/src/main/resources/application-server.yml, server/src/main/resources/application.yml
어떤 종류의 PR인가요?
Issue Number: #149
=> [Server] 사료주고받기 오류수정, 글검색기능구현, 글조회queryDsl로 리팩토링

client/src/api/subscribe.ts, client/src/components/MyPage/FollowPopUp.tsx, client/src/components/MyPage/FollowerPopUp.tsx, client/src/components/MyPage/UnFollowPopUp.tsx, client/src/components/NoContent/NoContent.tsx, client/src/pages/Main/Main.tsx, client/src/pages/Main/style.ts, client/src/pages/MyPage/MyPage.tsx, client/src/pages/MyPage/MyPageArticles.tsx, client/src/pages/MyPage/MyPageComments.tsx, client/src/pages/MyPage/MyPageSnacks.tsx, client/src/pages/MyPage/style.ts, client/src/pages/Profiles/ProfileArticles.tsx, client/src/pages/Profiles/ProfileSnacks.tsx, client/src/pages/Profiles/Profiles.tsx, client/src/pages/Profiles/style.ts
어떤 종류의 PR인가요?
Issue Number: #74 
* 메인페이지 배너에 맞게 css 수정
* 마이페이지 탭 & 팔로우, 팔로워 목록 모달에 데이터가 없을 때 빈 페이지 구현
* 팔로우, 팔로워 모달 구현
* 프로필 페이지 탭 & 팔로우, 팔로워 목록 모달에 데이터가 없을 때 빈 페이지 구현
* api 추가 수정된 부분 반영
* NoContent 파일 공통 컴포넌트로 제작(고독 냥이)
* 프로필 페이지에서 팔로우 취소 시 확인 모달 구현
* 로그인 안 한 상태에서 팔로우 버튼 클릭 -> 로그인 요청 알림 구현
=> [Client] 마이페이지 기능 구현 2차 완료

server/src/main/resources/application.yml, server/src/main/resources/templates/login.html
어떤 종류의 PR인가요?
Issue Number: #136 
oauth2 리다이렉트 주소 수정
=> [Server] ♻️ fix: oauth redirect 주소 수정

server/src/main/java/com/cocoa/catdog/user/controller/UserController.java, server/src/main/java/com/cocoa/catdog/user/service/UserService.java
=> 🐛 fix: 이미지 업이 회원가입, 회원수정 되도록 버그 수정 #105

client/src/_state/mainLIstState.tsx, client/src/components/Detail/ArticleLikeAndSnack/ArticleLikeAndSnack.tsx, client/src/components/TopButton/TopButton.tsx, client/src/pages/Main/Main.tsx, client/src/pages/MyPage/MyPageArticles.tsx, client/src/pages/MyPage/MyPageSnacks.tsx, client/src/pages/Profiles/ProfileSnacks.tsx
어떤 종류의 PR인가요?
Issue Number: #74
Issue Number: #57 
* 상세 페이지에서 좋아요, 간식 변경하면 메인페이지에 실시간 적용
* 글 목록 조회 api 데이터를 전역 상태관리로 변경
* 메인페이지 top 버튼 구현
* 마이페이지 게시물탭에서 내가 올린글 / 간식을 준 글 api 요청이 무시되는 현상 발견 -> 에러 해결
=> [Client] 메인 페이지 좋아요, 간식 실시간 적용 및 마이페이지 에러 해결

server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java, server/src/main/java/com/cocoa/catdog/article/entity/Article.java, server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustom.java, server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustomImpl.java, server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java, server/src/main/java/com/cocoa/catdog/user/entity/User.java, server/src/main/java/com/cocoa/catdog/user/service/UserService.java, server/src/main/resources/application.yml
어떤 종류의 PR인가요?
Issue Number: #155
=> [Server] 신고에 따른 블락처리

server/src/main/java/com/cocoa/catdog/auth/handler/OAuth2MemberSuccessHandler.java, server/src/main/resources/application.yml
어떤 종류의 PR인가요?
Issue Number: #136 
SMTP 비밀번호 환경변수 적용
=> [Server] ♻️ fix: SMTP 비밀번호 환경변수 적용

server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustomImpl.java
어떤 종류의 PR인가요?
Issue Number: #160
=> 🐛 bug: 글목록 중복오류 수정

server/src/main/java/com/cocoa/catdog/auth/handler/OAuth2MemberSuccessHandler.java, server/src/main/resources/application.yml
어떤 종류의 PR인가요?
Issue Number: #158 
구글 리다이렉트 주소 환경 변수 적용 ${GOOGLE_OAUTH_REDIRECT}
가입여부 (sign) 과 추가정보 (info) 필요에 따라 리턴 주소에 파라미터 추가
=> ♻️ fix: 가입상태와 기본정보유무에 따른 파라미터 추가

server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java, server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java, server/src/main/java/com/cocoa/catdog/article/mapper/ArticleMapper.java, server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustom.java, server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustomImpl.java, server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
어떤 종류의 PR인가요?
Issue Number: #160
=> 🐛 bug: 마이페이지 중복오류 수정

server/src/main/java/com/cocoa/catdog/auth/handler/OAuth2MemberSuccessHandler.java
=> ♻️ fix: 구글 리다이랙션 주소 배포용으로 변경

client/src/components/Header/Header.tsx
=> fix: 로고 누를시 새로고침되는 오류 수정

client/src/components/TopButton/TopButton.tsx, client/src/pages/MyPage/MyPage.tsx, client/src/pages/Profiles/ProfileArticles.tsx, client/src/pages/Profiles/Profiles.tsx
=> [Client] OuterComponent 스타일 속성 적용, 탑버튼 css 수정

client/src/api/mypage.ts, client/src/components/Header/Header.tsx, client/src/pages/Main/Main.tsx, client/src/pages/Main/style.ts, client/src/pages/MyPage/MyPage.tsx, client/src/pages/MyPage/MyPageArticles.tsx, client/src/pages/MyPage/MyPageComments.tsx, client/src/pages/MyPage/MyPageSnacks.tsx, client/src/pages/Profiles/ProfileArticles.tsx, client/src/pages/Profiles/ProfileSnacks.tsx, client/src/pages/Profiles/Profiles.tsx
어떤 종류의 PR인가요?
Issue Number: #74 
* QA시 나왔던 문제 해결
* 모바일 화면에서 새로고침 시 observer 미관측으로 스크롤을 내려야 api 요청이 가는 에러 발생 -> 해결
* 마이페이지 게시물탭 간식을 준 글에서 articleId가 중복되어 에러 발생 -> 해결
* 무한스크롤 코드 리팩토링 진행
* 마이페이지 댓글탭, 간식탭 / 프로필 페이지 댓글탭 무한스크롤, 로딩 인디케이터 적용
* 마이페이지, 프로필 페이지에 top 버튼 추가
=> [Client] 무한스크롤 리팩토링, 게시물탭 중복 에러 해결

client/src/components/Articles/PhotoUpload/style.ts, client/src/components/Articles/WriteArticle/WriteArticle.tsx, client/src/components/Modal/style.ts, client/src/components/Setting/DeleteAccount/DeleteAccount.tsx, client/src/components/Shop/Items/Item/Item.tsx, client/src/pages/Shop/Shop.tsx
어떤 종류의 PR인가요?
- 비밀번호가 일치하지 않아도 회원탈퇴되는 오류 수정
- 상점 페이지 수량 적용 안되는 오류 수정
- 상점 페이지 교환 성공시 안내 메세지 추가
- 글 작성시 작은 이미지 넣어도 UI 정상적으로 나오도록 수정
- 글 작성시 글자수 제한 알림
- 모달 이전, 다음 크기 키움
=> [Client] 피드백받은 부분 수정

server/src/main/java/com/cocoa/catdog/auth/handler/OAuth2MemberSuccessHandler.java, server/src/main/java/com/cocoa/catdog/config/SecurityConfiguration.java, server/src/main/resources/application-h2.yml
어떤 종류의 PR인가요?
Issue Number: #181 
구글 리다이랙션 주소 SSL 적용
시큐리티 내 OPTIONS 메소드 허용 추가
=> ♻️ fix: 구글 리다이랙션 주소 SSL 적용, 시큐리티 OPTIONS 추가

server/src/main/java/com/cocoa/catdog/config/aws/S3Service.java, server/src/main/resources/application-server.yml, server/src/main/resources/application.yml
=> ✨ feat: url을 s3 -> cdn 주소로 수정
